<?php

/**
 * @file
 * pdf reader module file.
 */

/**
 * Implements hook_permission().
 */
function pdf_reader_permission() {
  return array(
    'administer pdf reader' => array(
      'title' => t('Administer PDF Reader'),
      'description' => t('Perform maintenance tasks for PDF Reader'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function pdf_reader_menu() {
  $items['admin/config/pdf/reader'] = array(
    'title' => 'PDF Reader',
    'description' => 'Manage PDF Reader display format.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pdf_reader_admin_settings'),
    'access arguments' => array('administer pdf reader'),
    'file' => 'pdf_reader.admin.inc',
  );

  return $items;
}

/**
 * Implement hook_field_formatter_info().
 */
function pdf_reader_field_formatter_info() {
  return array(
    'pdf_reader_file' => array(
      'label' => t('PDF Reader'),
      'field types' => array('file'),
      'settings' => array(
        'pdf_width' => 600,
        'pdf_height' => 780,
        'renderer' => 'Google Viewer'
      )
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function pdf_reader_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element['pdf_width'] = array(
    '#title' => t('Width'),
    '#type' => 'textfield',
    '#default_value' => $settings['pdf_width'],
  );

  $element['pdf_height'] = array(
    '#title' => t('Height'),
    '#type' => 'textfield',
    '#default_value' => $settings['pdf_height'],
  );

  $element['renderer'] = array(
    '#title' => t('Renderer'),
    '#type' => 'select',
    '#options' => array('Google Viewer', 'Zoho Viewer', 'Direct Embed'),
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function pdf_reader_field_formatter_settings_summary($field, $instance, $view_mode) {
  $renderers = array('Google Viewer', 'Zoho Viewer', 'Direct Embed');
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = 'Size: ' . $settings['pdf_width'] . 'x' . $settings['pdf_height'] . ' Using: ' . $renderers[$settings['renderer']];
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function pdf_reader_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $settings = $display['settings'];
  $element = array();

  switch ($display['type']) {
    case 'pdf_reader_file':
      foreach ($items as $delta => $item) {
        $element[$delta]['#type'] = 'markup';
        $element[$delta]['#markup'] = theme('pdf_reader', array('file' => $item, 'settings' => $settings));
      }
      break;
  }

  return $element;
}

/**
 * Implements hook_theme().
 *
 * Use our theme function.
 */
function pdf_reader_theme($existing, $type, $theme, $path) {
  return array('pdf_reader' => array(
    'variables' => array('file' => NULL, 'settings' => NULL)
  ));
}

/**
 * Theme the field with pdf reader
 */
function theme_pdf_reader($variables) {
  switch ($variables['settings']['renderer']) {
    case 0:
    default:
      $output = '<iframe src="http://docs.google.com/viewer?embedded=true&url='
              . urlencode(file_create_url($variables['file']['uri']))
              . '" width="' . $variables['settings']['pdf_width']
              . '" height="' . $variables['settings']['pdf_height']
              . '" style="border: none;"></iframe>';
      break;
    
    case 1: 
      $output = '<iframe src="https://viewer.zoho.com/docs/urlview.do?embed=true&url='
              . urlencode(file_create_url($variables['file']['uri']))
              . '" width="' . $variables['settings']['pdf_width']
              . '" height="' . $variables['settings']['pdf_height']
              . '" style="border: none;"></iframe>';
    
    case 2: 
      $output = '<object data="' . file_create_url($variables['file']['uri']) . '#view=Fit' . '" '
              . 'type="application/pdf' . '" '
              . 'width="' . $variables['settings']['pdf_width'] . '" '
              . 'height="' . $variables['settings']['pdf_height'] . '">'
              . '<embed src="' . file_create_url($variables['file']['uri']) . '#view=Fit' . '"'
              . 'width="' . $variables['settings']['pdf_width'] . '" '
              . 'height="' . $variables['settings']['pdf_height'] . '" '
              . 'type="application/pdf">'
              . '<p>' . t('It appears your Web browser is not configured to display PDF files. ')
              . l(t('Download adobe Acrobat '), 'http://www.adobe.com/products/reader.html')
              . ' ' . t('or') . ' ' . l(t('click here to download the PDF file.'), file_create_url($variables['file']['uri'])) . '</p>'
              . '</embed></object>';
      break;
  }
  
  return $output;
}
