<?php

/**
 * @file
 *   panparks_api.module
 * Project:panparks.org
 *    Api functions for panparks.org
 *
 * @developers:
 *    Gabor Szanto <hello@szantogabor.com>
 *    http://szantogabor.com
 *
 */

function panparks_api_action_info() {
  $actions = array();
  $actions['panparks_api_update_media'] = array(
    'type' => 'entity',
    'label' => t('Update media metadata'),
    'configurable' => FALSE,
  );
  $actions['panparks_api_fetch_img_id'] = array(
    'type' => 'entity',
    'label' => t('Fetch node id from img_assist code'),
    'configurable' => FALSE,
  );
  $actions['panparks_api_set_main_picture'] = array(
    'type' => 'entity',
    'label' => t('Set main picture'),
    'configurable' => FALSE,
  );
  return $actions;
}

/*
 * Helper function actualize media data after importing.
 */

function panparks_api_update_media($entity, $context) {
  $fid = $entity->field_image['und'][0]['fid'];
  $media = file_load($fid);
  if ($entity->title != 'photo') {
    $media->media_title['und'][0]['value'] = $entity->title;
  }
  if (!empty($entity->field_photographer)) {
    //@todo: need more transform?
    $photographer = str_replace('Photo:', '', $entity->field_photographer['und'][0]['value']);
    //$photographer = str_replace('Photo:', '', $$photographer);
    $media->field_photographer['und'][0]['value'] = $photographer;
  }
  if (!empty($entity->field_old_gallery_nid)) {
    $media->field_old_gallery_nid['und'][0]['value'] = $entity->field_old_gallery_nid['und'][0]['value'];
  }
  if (!empty($entity->field_old_tid)) {
    $media->field_old_tid['und'][0]['value'] = $entity->field_old_tid['und'][0]['value'];
  }
  $media->field_old_nid['und'][0]['value'] = $entity->field_old_nid['und'][0]['value'];
  if ($folder_term = taxonomy_get_term_by_name($entity->field_old_term_name['und'][0]['value'])) {
    foreach ($folder_term as $key => $value) {
      $folder_tid = $key;
    }
    $media->field_folder['und'][0]['tid'] = $folder_tid;
  }
  else $media->field_folder['und'][0]['tid'] = 24;
  file_save($media);
  //dsm(get_defined_vars());
}

/*
 * Helper function to get image nid from image assist code.
 */

function panparks_api_fetch_img_id($entity, $context) {
  $source = $entity->field_tmp_imgtext['und'][0]['value'];
  if (preg_match('/(nid=)([0-9]*)/', $source, $target)) {
    $entity->field_tmp_img_nid['und'][0]['value'] = $target[2];
    node_save($entity);
  }
}

/*
 * Helper function actualize media data after importing.
 */

function panparks_api_set_main_picture($entity, $context) {

}