<?php

/**
 * @file
 *   panparks_photo.module
 * Project:panparks.org
 *    Photo share functions for panparks.org
 *
 * @developers:
 *    Tamas Pinter <tamas@netstandard.hu>
 *    http://netstandard.hu
 *
 */

/**
 * Implementation of hook_form_photo_shared_node_form_alter().
 */
function panparks_photo_form_photo_shared_node_form_alter(&$form, $form_state) {
  // Get involved -  get-involved
//  We love wildlife - get-involved/we-love-wildlife
  $bc = drupal_get_breadcrumb();
  $end = array_pop($bc);
  $bc[] = l('Get involved', 'get-involved');
  $bc[] = l('We love wildlife', 'get-involved/we-love-wildlife');

  if (empty($form['#node']->nid)) {
    //    $form['field_ps_geo']['#access'] = FALSE;
    $form['field_gallery']['#access'] = FALSE;
    $form['field_species']['#access'] = FALSE;
    $form['field_general']['#access'] = FALSE;
    $form['field_orientation']['#access'] = FALSE;
    $form['field_subject']['#access'] = FALSE;
    $form['field_ps_individual']['#access'] = FALSE;
    $form['field_approved']['#access'] = FALSE;
  }
  else {
    $bc[] = $end;
    $form['field_ps_legal']['#disabled'] = TRUE;

    if ($form['#node']->field_approved['und'][0]['value'] > 0) {
      $form['field_approved']['#disabled'] = TRUE;
    }
  }
//  $form['#after_build'][] = 'panparks_photo_after_build';
  $form['field_ps_moderated']['#access'] = FALSE;

  drupal_set_breadcrumb($bc);
}

/**
 * Implements hook_node_validate().
 */
function panparks_photo_node_validate($node, $form, $form_state) {
  if ($node->type == 'photo_shared') {
    if ($node->nid) {
      if ($form_state['values']['field_approved']['und'][0]['value'] < 1) {
        form_set_error('field_approved', t('The image has not been moderated!'));
      }
    }
    else {
      $link = !empty($form_state['values']['field_ps_link']['und'][0]['url']);
      $photo = $form_state['values']['field_ps_photo']['und'][0]['fid'];

      if ($link && $photo) {
        form_set_error('field_ps_photo_via', t("Don't fill both Photo and Link field!"));
      }

      if (!$link && !$photo) {
        form_set_error('field_ps_photo_via', t('Photo or Link field is required'));
      }

      $errors = drupal_get_messages('error');
      foreach ($errors['error'] AS $message) {
        if ($message == t('I accept the Terms and Conditions field is required.')) {
          drupal_set_message('Without acceptance of terms and conitions upload of pictures is not allowed.', 'error');
        }
        else {
          drupal_set_message($message, 'error');
        }
      }
    }
  }
}
